name: PR Merge Commit Range Reporter

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  report-commit-range:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Determine commit range and report
        id: report
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const { owner, repo } = context.repo;

            // Fetch all commits in this PR (handles pagination)
            const commits = await github.paginate(
              github.rest.pulls.listCommits,
              { owner, repo, pull_number: pr.number, per_page: 100 }
            );

            if (!commits.length) {
              core.setFailed('No commits found in this PR.');
              return;
            }

            const startSha = commits[0].sha;
            const endSha = commits[commits.length - 1].sha;
            const headRef = pr.head.ref; // PR branch name
            const baseRef = pr.base.ref; // target branch name

            core.info(`Head branch: ${headRef}`);
            core.info(`Base branch: ${baseRef}`);
            core.info(`Start commit SHA: ${startSha}`);
            core.info(`End commit SHA: ${endSha}`);

            // Expose as outputs (in case other steps need them later)
            core.setOutput('start_sha', startSha);
            core.setOutput('end_sha', endSha);
            core.setOutput('head_ref', headRef);
            core.setOutput('base_ref', baseRef);

            // Job Summary for quick viewing in the Actions UI
            await core.summary
              .addHeading('PR Merge Commit Range')
              .addRaw(`PR #${pr.number} merged: ${pr.title}`, true)
              .addTable([
                [{ data: 'Head Branch', header: true }, headRef],
                [{ data: 'Base Branch', header: true }, baseRef],
                [{ data: 'Start SHA', header: true }, startSha],
                [{ data: 'End SHA', header: true }, endSha],
              ])
              .addLink('View PR', pr.html_url)
              .write();

            // Comment on the PR with the SHAs
            const body = [
              `This PR has been merged.`,
              `Head branch: ${headRef}`,
              `Base branch: ${baseRef}`,
              `Start commit SHA: ${startSha}`,
              `End commit SHA: ${endSha}`,
            ].join('\n');

            try {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: pr.number,
                body,
              });
            } catch (err) {
              core.warning(`Failed to comment on PR (likely due to permissions on forked PRs): ${err.message}`);
            }
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Create cherrypick branch and cherry-pick range
        id: cherry_pick
        shell: bash
        env:
          START_SHA: ${{ steps.report.outputs.start_sha }}
          END_SHA: ${{ steps.report.outputs.end_sha }}
        run: |
          set -euo pipefail
          BRANCH="cherrypick/${{ github.event.pull_request.number }}"
          echo "Branch: $BRANCH"
          echo "Cherry-picking range: ${START_SHA}^..${END_SHA}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch --all --prune
          git checkout -B "$BRANCH" "origin/release-1.0"
          if ! git cherry-pick "${START_SHA}^..${END_SHA}"; then
            echo "Cherry-pick failed, aborting."
            git cherry-pick --abort || true
            exit 1
          fi
          # Try to push branch
          if ! git push -u origin "HEAD:$BRANCH"; then
            echo "Initial push failed, attempting force-with-lease"
            git push -u origin "HEAD:$BRANCH" --force-with-lease
          fi
      - name: Open PR to release-1.0
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const { owner, repo } = context.repo;
            const startSha = `${{ steps.report.outputs.start_sha }}`;
            const endSha = `${{ steps.report.outputs.end_sha }}`;
            const branch = `cherrypick/${pr.number}`;
            const title = `Cherry-pick PR #${pr.number} into release-1.0`;
            const body = [
              `This is an automated cherry-pick of PR #${pr.number} into release-1.0.`,
              '',
              `Commit range: ${startSha}^..${endSha}`,
            ].join('\n');
            try {
              const resp = await github.rest.pulls.create({
                owner,
                repo,
                head: branch,
                base: 'release-1.0',
                title,
                body,
                maintainer_can_modify: true,
              });
              core.info(`Created PR: ${resp.data.html_url}`);
              await core.summary
                .addHeading('Cherry-pick PR Created')
                .addLink('View PR', resp.data.html_url)
                .write();
            } catch (err) {
              core.warning(`Failed to create PR (it may already exist or permissions are insufficient): ${err.message}`);
            }

      - name: Comment compare link to cherry-pick branch
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const { owner, repo } = context.repo;
            const compareUrl = `https://github.com/${owner}/${repo}/compare/release-1.0...cherrypick/${pr.number}`;
            const body = `Compare link for cherry-pick branch:\n${compareUrl}`;
            try {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: pr.number,
                body,
              });
              core.info(`Commented compare link: ${compareUrl}`);
            } catch (err) {
              core.warning(`Failed to comment compare link: ${err.message}`);
            }
