name: Backport release PR to release-1.0

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  backport:
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Ensure target branch exists
        run: |
          git ls-remote --exit-code --heads origin release-1.0 >/dev/null || {
            echo "::error::Target branch 'release-1.0' not found"; exit 1; }

      - name: Create backport branch off release-1.0
        env:
          PRNUM: ${{ github.event.pull_request.number }}
        run: |
          git fetch origin release-1.0
          BP="backport/pr-${PRNUM}-to-release-1.0"
          git checkout -B "$BP" origin/release-1.0
          echo "BP=$BP" >> "$GITHUB_ENV"

      - name: Apply PR diff onto release-1.0
        run: |
          PRNUM=${{ github.event.pull_request.number }}
          git fetch origin pull/$PRNUM/head:pr-$PRNUM
          git checkout "$BP"
          # Merge the PR branch into release-1.0 without committing, allow conflicts
          git merge --no-commit --no-ff "pr-$PRNUM" || true
          git commit -am "Backport PR #$PRNUM to release-1.0 (with conflicts to resolve)" || true

      - name: Push backport branch
        run: git push --set-upstream origin "$BP"

      - name: Comment backport branch on source PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
          --body "📌 A backport branch has been created: \`${BP}\`. Please open a PR from it into \`release-1.0\`."
