name: Backport release PR to release-1.0

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Merged PR number to backport"
        required: true
        type: string

jobs:
  backport:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' &&
       github.event.action == 'closed' &&
       github.event.pull_request.merged == true &&
       contains(github.event.pull_request.labels.*.name, 'release'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Resolve PR number
        id: pr
        run: |
          PR="${{ github.event.pull_request.number }}"
          if [ -z "$PR" ]; then PR="${{ inputs.pr_number }}"; fi
          echo "NUMBER=$PR" >> $GITHUB_OUTPUT

      - name: Get first and last commit in PR
        id: commits
        run: |
          COMMITS=$(gh api \
            repos/${{ github.repository }}/pulls/${{ steps.pr.outputs.NUMBER }}/commits \
            --paginate -F per_page=100 --jq '.[].sha')
          FIRST=$(printf "%s\n" "$COMMITS" | head -n1)
          LAST=$(printf "%s\n" "$COMMITS" | tail -n1)
          echo "FIRST=$FIRST" >> $GITHUB_OUTPUT
          echo "LAST=$LAST"  >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment cherry-pick command
        run: |
          gh pr comment ${{ steps.pr.outputs.NUMBER }} --body \
            "To replay this PR on another branch, run:

            \`\`\`bash
            git cherry-pick ${{ steps.commits.outputs.FIRST }}^..${{ steps.commits.outputs.LAST }}
            \`\`\`"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
